name: check links

on:
  schedule:
    - cron: '42 04 * * *'
  pull_request:
    branches:
      - "*"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: create .lycheeignore
        run: |
          echo "*.jpg" >> .lycheeignore
          echo "*.png" >> .lycheeignore
          echo "*.pdf" >> .lycheeignore
          echo "*.webp" >> .lycheeignore
          echo "*formspree.io*" >> .lycheeignore
          echo "*mindthemath.com*" >> .lycheeignore

      - name: cheeck links
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: --verbose './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: create issue
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated
