name: check links

on:
  schedule:
    - cron: '42 04 */4 * *'
  pull_request:
    branches:
      - "*"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: create .lycheeignore
        run: |
          echo "[a-zA-Z]*[0-9]*.jpg" >> .lycheeignore
          echo "[a-zA-Z]*[0-9]*.png" >> .lycheeignore
          echo "[a-zA-Z]*[0-9]*.pdf" >> .lycheeignore
          echo "[a-zA-Z]*[0-9]*.webp" >> .lycheeignore
          echo "https://formspree.io[a-zA-Z]*[0-9]*" >> .lycheeignore
          echo "https://www.linkedin.com/in/[a-zA-Z]*[0-9]*" >> .lycheeignore
          echo "https://mindthegrow.com/[a-zA-Z]*[0-9]*" >> .lycheeignore

      - name: check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: --verbose './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: create issue
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated
