name: Staging

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"
      - ".github/workflows/*"

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"

jobs:
  stage:
    runs-on: io
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          #submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: false

      - name: get hash
        id: vars
        run: |
         echo "::set-output name=sha_short::$(git rev-parse --short HEAD^2)"

      - name: build hash
        run: hugo --baseURL=http://clfx.cc/mm/${{ steps.vars.outputs.sha_short }}

      - name: deploy hash
        run: |
          mkdir -p ~/out/mm/${{ steps.vars.outputs.sha_short }}
          cp -R public/* ~/out/mm/${{ steps.vars.outputs.sha_short }}/

      - name: build stage
        run: hugo --baseURL=http://clfx.cc/mm/stage

      - name: deploy stage
        run: |
          rm -rf ~/out/mm/stage
          mkdir -p ~/out/mm/stage
          cp -R public/* ~/out/mm/stage

      - name: find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview

      - name: update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview of ${{ steps.vars.outputs.sha_short }}: https://clfx.cc/mm/${{ steps.vars.outputs.sha_short }}
          edit-mode: append
