name: Staging

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"
      - ".github/workflows/*"

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"

jobs:
  stage:
    runs-on: io
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          #submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: false

      - name: build
        run: hugo --baseURL=http://clfx.cc/"$GITHUB_SHA"

      - name: deploy
        run: |
          mkdir -p ~/out/"$GITHUB_SHA"
          cp -R public/* ~/out/"$GITHUB_SHA"/

