name: Staging

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"

jobs:
  stage:
    runs-on: io
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          #submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: false

      - name: get hash
        id: vars
        shell: bash
        run: |
          if [ ${{github.event_name}} -eq 'pull_request' ]; then
            echo "::set-output name=sha_short::$(git rev-parse --short HEAD^2)"
            echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD^2)"
          else
            echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
          fi

      - name: build hash
        run: hugo --baseURL=http://clfx.cc/mm/${{ steps.vars.outputs.sha_short }}

      - name: deploy hash
        run: |
          mkdir -p ~/out/mm/${{ steps.vars.outputs.sha_short }}
          cp -R public/* ~/out/mm/${{ steps.vars.outputs.sha_short }}/

      - name: build stage
        run: hugo --baseURL=http://clfx.cc/mm/${{ steps.vars.outputs.branch }}

      - name: deploy stage
        run: |
          rm -rf ~/out/mm/${{ steps.vars.outputs.branch }}
          mkdir -p ~/out/mm/${{ steps.vars.outputs.branch }}
          cp -R public/* ~/out/mm/${{ steps.vars.outputs.branch }}

- name: find staging comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request'
        id: oc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Staging

      - name: update staging comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request'
        with:
          comment-id: ${{ steps.oc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Staging: ${{ steps.vars.outputs.sha_short }}: https://clfx.cc/mm/${{ steps.vars.outputs.branch }}
          edit-mode: replace

      - name: find revision comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview

      - name: update revision comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request'
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview of ${{ steps.vars.outputs.sha_short }}: https://clfx.cc/mm/${{ steps.vars.outputs.sha_short }}
          edit-mode: append
