name: Staging

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"
      - ".github/workflows/*"

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "docker/*"

jobs:
  stage:
    runs-on: io
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          #submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: false

      - name: build hash
        run: hugo --baseURL=http://clfx.cc/mm/${{ github.sha }}

      - name: deploy hash
        run: |
          mkdir -p ~/out/mm/${{ github.sha }}
          cp -R public/* ~/out/mm/${{ github.sha }}/

      - name: build stage
        run: hugo --baseURL=http://clfx.cc/mm/stage

      - name: deploy stage
        run: |
          rm -rf ~/out/mm/stage
          mkdir -p ~/out/mm/stage
          cp -R public/* ~/out/mm/stage
          
